create table kn_ways_new ();
select addgeometrycolumn('kn_ways_new', 'the_geom', 4326, 'LINESTRING', 2);
alter table kn_ways_new add column length double precision;
insert into kn_ways_new (the_geom, length) select the_geom, length from kn_ways;
create index the_geom_idx1 on kn_ways_new using gist(the_geom);
alter table kn_ways_new add column z_id BIGSERIAL;
alter table kn_dem_clip_finer add column the_geom_st_envelope geometry;
update kn_dem_clip_finer set the_geom_st_envelope = st_envelope(rast);
create index the_geom_st_envelope_idx on kn_dem_clip_finer using gist(the_geom_st_envelope);
create table kn_ways_new_split (the_geom geometry, z_id bigserial);
